### ISSUE TITLE
Exception when using in BottomSheetFragment

### ISSUE THREAD

**Issue by pradeep-orbi** [arteaprogramar/Android-MaterialFilePicker#2]
This is the code i'm using 
             MaterialFilePicker()
                .withSupportFragment(this)
                // With cross icon on the right side of toolbar for closing picker straight away
                .withCloseMenu(true)
                // Showing hidden files
                .withHiddenFiles(true)
                // Want to choose only pdf files
                .withFilter(Pattern.compile(".*\\.(pdf)$"))
                // Don't apply filter to directories names
                .withFilterDirectories(false)
                .withTitle("Select PDF file to upload")
                .withRequestCode(FILE_PICKER_REQUEST_CODE)
                .start()

    java.lang.RuntimeException: Unable to start activity 
ComponentInfo{/arte.programar.materialfile.ui.FilePickerActivity}: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x1010031 a=2 r=0x7f06004d}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2925)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x1010031 a=2 r=0x7f06004d}
        at android.content.res.TypedArray.getColor(TypedArray.java:477)
        at android.app.Activity.onApplyThemeResource(Activity.java:4383)
        at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:198)
        at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:140)
        at android.app.Activity.setTheme(Activity.java:4354)
        at androidx.appcompat.app.AppCompatActivity.setTheme(AppCompatActivity.java:120)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2898)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by pradeep-orbi** [comment]
It is working after adding colors and styles mentioned in the documentation
